### ISSUE TITLE
xdotool key & xdotool type both repeating with an extra enter in between in bash or tcsh but not dash

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [jordansissel/xdotool#195]
Observed:
$ xdotool key a
a$ a

Expected:
$ xdotool key a
a$ 

- - - - - - - - -

Observed:
$ xdotool type "aaaaaaa"
aaaaaaa$ aaaaaaa

Expected:
$ xdotool type "aaaaaaa"
aaaaaaa$

It seems to be sending the key simulations I expect, then a newline, then the keys it already sent AGAIN.
This does not happen with modified keys commands like `xdotool key ctrl+a` nor with `xdotool key Delete`. It hapens in:

GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
 and 
tcsh 6.18.01 (Astron) 2012-02-14 (x86_64-unknown-linux) options wide,nls,dl,al,kan,rh,nd,color,filec
 but NOT in
dash 0.5.8-2.1ubuntu2

In dash, things work as expected. This is in Ubuntu 16.04 LTS, 64 bit, built from the mini.iso, with plain Openbox under X11, running xdotool version 3.20150503.1.

Tested in lxterminal, terminator, xvt, rxvt, & xterm, with same result.
Anything I can do to help track the reason down? Or is it something dumb I've done locally? Could this have anything to do with the prompt settings? I set bash to have a different prompt in a tty than in a terminal in Openbox. I'm hazy on the details of how I did that, but FWIW in a terminal:

$ echo $PS1
${debian_chroot:+($debian_chroot)}\[\033[37;44m\]\$\[\033[00m\]
$ tcsh
Ux:~> echo $PS1
echo: No match.
Ux:~> exit
exit
$ dash
\[\033[37;44m\]$\[\033[00m\] echo $PS1
${debian_chroot:+($debian_chroot)}\[\]\$\[\]
\[\033[37;44m\]$\[\033[00m\] 
\[\033[37;44m\]$\[\033[00m\] exit
$ 

I never monkeyed with tcsh or dash specific files to adjust the prompt as I recall. Concievably (from my perspective or relative ignorance) tcsh might consult some file in common with bash that dash ignores. I can dig into that if you think it could be relevant.

**Comment by antofthy** [comment]
This is normal behaviour.
xdotool is actually typing the string as if you typed it yourself on the keyboard.
As such while it was running the computer thinks you types something and echos it.
the shell then comes along and read the keys (thought to come from keyboard) and echos them again as the command.  It is part of tcsh and bashs command line editing system.   Dash does not have a command line editing system so does not echo the characters again.

Try this...    run the command "sleep 5" and while the command is running type letters on the keyboard.  When the sleep finishes, you will get exactly the same result as you manually did what xdotool did, for the shell you are using.

It is expected behaviour!  and the command is doing exactly what you asked it to do -- type some characters as if it came from the keyboard, immediately into the current window (the terminal)

**Comment by Lew-Rockwell-Fan** [comment]
I can't honestly say I understand your point about command line editing, but

> Normally you would have a program type the characters.. For example try this.
> sleep 5; xdotool type "Hi"
> now switch to another terminal window

is quite enlightening. That is analagous to what I was doing when I discovered this - using xdotool to type into an entry field of a focused gui program - & this time it did exactly what it "should" & what I had originally expected. I "discovered" this faux bug when debugging that script by trying one line in a terminal.

OK, the part I do understand is that I have to be more careful how I debug any script involving a command that acts on the focused window & to get a clearer picture by not having that window be the terminal I'm testing the command in.

So, thanks, that helps - now I know one way NOT to debug a script - & this is really not an xdotool issue  but some bash-in-a-terminal weirdness that I don't understand.
