### ISSUE TITLE
getmouselocation should put window ID on the window stack

### ISSUE THREAD

**Issue by rustyx** [jordansissel/xdotool#379]
Here's a simple suggestion to make `getmouselocation` store the found window ID on the stack.

So that chaining like `xdotool getmouselocation windowminimize` works.

Currently it doesn't, and I'm forced to jump through hoops like `xdotool windowminimize $(xdotool getmouselocation|sed "s/.*://")`

**Comment by jordansissel** [comment]
I like this idea. I think xdotool already does this, from #322! I looked at the code, and the window is saved to the stack if:
* `--shell` is _not_ used
* and `getmouselocation` is not the last command

https://github.com/jordansissel/xdotool/blob/735e301665e7f9b8fe850588e88a3a0973695eec/cmd_getmouselocation.c#L55-L61

I don't have a great system to test on right now since my desktop uses Wayland (has known issues with xdotool), but if I do this:

```
% xev &

% sleep 3; xdotool getmouselocation windowminimize
```


If before the `sleep 3` finishes, my mouse moves to hover over the `xev` window, then xev will minimize. It also works for `xterm` windows when the mouse is over it.

It doesn't seem to work with gnome-terminal or firefox, though. This might have to do with some oddities in X11 that I think we can try to fix. In X11, windows can have sub-windows, and getmouselocation might hover hover a "subwindow" and minimizing *that* might have no effect -- when the correct behavior would be to minimize the application window itself.


I'll do some digging and see what I can learn.

**Comment by jordansissel** [comment]
I tested some things out on X11, and everything I've tried works as I'd expect:

For `xdotool getmouselocation windowminimize`:
* firefox will minimize
* xterm will minimize 
* gnome-terminal will minimize 

#322 was merged in February 2021 which added this feature. It should be available in version 3.20210804.1 or newer.

https://github.com/jordansissel/xdotool/blob/735e301665e7f9b8fe850588e88a3a0973695eec/CHANGELIST#L34-L35

**Comment by jordansissel** [comment]
If for some reason you can't upgrade, you might find the `--shell` flag easier than using `sed`

```
% eval "$(xdotool getmouselocation --shell)"
% xdotool windowminimize $WINDOW
```

**Comment by rustyx** [comment]
Oh nice, indeed the latest version is working fine! Thanks!!
I'm using [xdotool from Debian 11 (bullseye)](https://packages.debian.org/bullseye/source/xdotool), version 3.20160805.1. (I wonder why a Debian release from 2021 is using such an old version?)
