### ISSUE TITLE
How to type quotes?

### ISSUE THREAD

**Issue by gerw** [jordansissel/xdotool#72]
Is it possible to type quotes (" and ')?

I would like to use http://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu also for passwords containing quotes.

In particular, the following does not produce the expected output (tried with master):

    xdotool - <<< "type --clearmodifiers -- '"
    xdotool - <<< "type --clearmodifiers -- \""

I expected to see ' and ", but actually, nothing is produced.

**Comment by r8b7xy** [comment]
This fixes passwords with whitespaces and double quotes but breaks the passwords with single quotes:
```bash
-    xdotool - <<<"type --clearmodifiers -- $(pass show "$password" | head -n 1)"
+    xdotool - <<<"type --clearmodifiers -- '$(pass show "$password" | head -n 1)'"
```
RESULT:
"c?}xG$si"z{cov/K<g!!fwUZ^66'QK'K#K:~"s&%"lS1'u%`dqp<!zI    (plain pass)
"c?}xG$si"z{cov/K<g!!fwUZ^66QK'K#K:~"s&%"lS1'u%`dqp<!zI'    (xdotool with above path)

I was trying to pass those special characters with escape code for each using printf %q:
```bash
-    xdotool - <<<"type --clearmodifiers -- $(pass show "$password" | head -n 1)"
+    var=$(pass show "$password" | head -n 1)
+    printf -v var %q "$var"
+    xdotool - <<<"type --clearmodifiers -- $var"
```
RESULT:
"c?}xG$si"z{cov/K<g!!fwUZ^66'QK'K#K:~"s&%"lS1'u%`dqp<!zI    (plain pass)
\"c\?\}xG\$si\"z\{cov/K\<g\!\!fwUZ\^66\'QK\'K#K:\~\"s\&%\"lS1\'u%\`dqp\<\!zI    (with above path)

xdotool don't interpret escape codes (backslashes) but printf prints all special characters.

Moreover testing with cat instead of xdotool:
```bash
-    xdotool - <<<"type --clearmodifiers -- $(pass show "$password" | head -n 1)"
+    var=$(pass show "$password" | head -n 1)
+    cat - <<<"$var"
```
Results with good interpretation of all characters so I conclude that there is a problem with xdotool behaviour which could be improved.

I know I can:
```bash
-    xdotool - <<<"type --clearmodifiers -- $(pass show "$password" | head -n 1)"
+    xdotool type --clearmodifiers -- "$(pass show "$password" | head -n 1)"
```
but this style is prone to grabbing xdotool with ps or similar tool - and this is a security flaw for sure.

Maybe @cdown or @carnager have few ideas how to handle this.

**Comment by gerw** [comment]
The problem seems to be the tokenization at https://github.com/jordansissel/xdotool/blob/master/xdotool.c#L352

I do not see a possible fix.

Maybe a more elegant way is to introduce a parameter which says 'read the keys to type from stdin', such that we could do
```shell
    xdotool type --clearmodifiers -stdin <<< "$(pass show "$password" | head -n 1)"
```
?

**Comment by carnager** [comment]
watching this issue. i see no possible solution right now.

**Comment by gerw** [comment]
Curiously, there is already an option that reads from stdin:

    pass show "$password" | head -n 1 | head -c -1 | xdotool type --clearmodifiers --file -

````head -c 1```` is needed to strip the trailing newline.

**Comment by cdown** [comment]
Thanks @gerw for the report and @r8b7xy for mentioning me so I'd see this. This definitely seems like a bug in the xdotool tokeniser, but I've committed a workaround upstream for now.

**Comment by gerw** [comment]
@cdown: I think your workaround introduces a new bug: ````tr -d '\n'```` only deletes all newlines, but does print all lines in the password file.

**Comment by cdown** [comment]
@gerw Ah yeah, I forgot people do that. I'll fix that.
